spring:
  application:
    name: spring-cqrs-eventsourcing
  
  datasource:
    url: jdbc:h2:mem:eventstore
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example: DEBUG
    org.springframework: INFO
    org.hibernate: INFO